[package]
name = "diff-rs"
version = "0.2.3"
authors = ["hedgar2017 <hedgar2017@gmail.com>"]
license = "MIT"
description = "Rust diff implementation"
edition = "2018"

[dependencies]
clap = "2.32.0"
chrono = "0.4.6"
diffs = "0.2.1"
