[package]
name = "diff-rs"
version = "0.2.0"
authors = ["hedgar2017 <hedgar2017@gmail.com>"]
license = "MIT"
description = "Rust diff implementation"

[dependencies]
diffs = "0.2.1"
chrono = "0.4.6"
clap = "2.32.0"
